insert into TB_BLG_CONT
(BLG_CONT_SEQ, TITLE, CONT_BDY)
values
(SEQ_BLG_CONT.NEXTVAL, 'hello', 'this is content body');
select * from TB_BLG_CONT;

ALTER USER SPRNG_BLG_USR IDENTIFIED BY 1515;

CREATE SEQUENCE
"SPRNG_BLG_USR"."SEQ_BLG_CMT"
MINVALUE 1;


-- SPRNG_BLG_USR.TB_BLG_CMT definition

CREATE TABLE "SPRNG_BLG_USR"."TB_BLG_CMT" 
   (	"BLG_CMT_SEQ" NUMBER(38,0) NOT NULL ENABLE, 
	"BLG_CONT_SEQ" NUMBER(38,0) NOT NULL ENABLE, 
	"CMT_BDY" NVARCHAR2(150) NOT NULL ENABLE, 
	"TMP_PW" VARCHAR2(64), 
	"INSERT_DT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "NEWTABLE_PK" PRIMARY KEY ("BLG_CMT_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "SPRNG_BLG_USR"."NEWTABLE_PK" ON "SPRNG_BLG_USR"."TB_BLG_CMT" ("BLG_CMT_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- SPRNG_BLG_USR.TB_BLG_CMT foreign keys

ALTER TABLE "SPRNG_BLG_USR"."TB_BLG_CMT" ADD CONSTRAINT "TB_BLG_CMT_TB_BLG_CONT_FK" FOREIGN KEY ("BLG_CONT_SEQ")
	  REFERENCES "SPRNG_BLG_USR"."TB_BLG_CONT" ("BLG_CONT_SEQ") ENABLE;
	  
	  
	  
	  
-- SPRNG_BLG_USR.TB_BLG_CONT definition

CREATE TABLE "SPRNG_BLG_USR"."TB_BLG_CONT" 
   (	"BLG_CONT_SEQ" NUMBER(38,0) NOT NULL ENABLE, 
	"TITLE" NVARCHAR2(256) NOT NULL ENABLE, 
	"CONT_BDY" NCLOB NOT NULL ENABLE, 
	"INSERT_DT" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "TB_BLG_CONT_PK" PRIMARY KEY ("BLG_CONT_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONT_BDY") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "SPRNG_BLG_USR"."TB_BLG_CONT_PK" ON "SPRNG_BLG_USR"."TB_BLG_CONT" ("BLG_CONT_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "SPRNG_BLG_USR"."SYS_IL0000076727C00003$$" ON "SPRNG_BLG_USR"."TB_BLG_CONT" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;